/*
 * PropertyTycoon Application by Zytom
 */
package zytom.proptycoon.view.NewGameMenu.ChoosePlayers;

import javax.swing.JButton;

/**
 *
 * @author utopia
 */
public class TokenPanel extends javax.swing.JPanel {

    /**
     * Creates new form TokenPanel
     */
    public TokenPanel() {
        initComponents();
        this.add(new JButton());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(64, 64));
        setMinimumSize(new java.awt.Dimension(64, 64));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
