/*
 * PropertyTycoon Application by Zytom
 */
package zytom.proptycoon.view.NewGameMenu;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenLabel;

/**
 *
 * @author utopia
 */
public class ChoosePlayersPanel extends javax.swing.JPanel {
    
    private TokenLabel[] tokenLabels;
    
    /**
     * Creates new form ChoosePlayersPanel
     */
    public ChoosePlayersPanel() {
        initComponents();
        try {
            tokenLabels = new TokenLabel[6];
            tokenLabels[0] = new TokenLabel(TokenLabel.TokenType.BOOT);
            tokenLabels[1] = new TokenLabel(TokenLabel.TokenType.SMARTPHONE);
            tokenLabels[2] = new TokenLabel(TokenLabel.TokenType.GOBLET);
            tokenLabels[3] = new TokenLabel(TokenLabel.TokenType.HATSTAND);
            tokenLabels[4] = new TokenLabel(TokenLabel.TokenType.CAT);
            tokenLabels[5] = new TokenLabel(TokenLabel.TokenType.SPOON);
            for (TokenLabel tokenLabel : tokenLAbels)
        } catch (IOException ex) {
            Logger.getLogger(ChoosePlayersPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoosePLayersLabel = new javax.swing.JLabel();
        chosenTokenPanel1 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel2 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel3 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel4 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel5 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel6 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        tokenPanel1 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel();
        tokenPanel2 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel();
        tokenPanel3 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel();
        tokenPanel4 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel();
        tokenPanel5 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel();
        tokenPanel6 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel();

        ChoosePLayersLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        ChoosePLayersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoosePLayersLabel.setText("Choose Players...");

        tokenPanel1.setMinimumSize(new java.awt.Dimension(64, 64));
        tokenPanel1.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout tokenPanel1Layout = new javax.swing.GroupLayout(tokenPanel1);
        tokenPanel1.setLayout(tokenPanel1Layout);
        tokenPanel1Layout.setHorizontalGroup(
            tokenPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tokenPanel1Layout.setVerticalGroup(
            tokenPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        tokenPanel2.setMinimumSize(new java.awt.Dimension(64, 64));
        tokenPanel2.setPreferredSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout tokenPanel2Layout = new javax.swing.GroupLayout(tokenPanel2);
        tokenPanel2.setLayout(tokenPanel2Layout);
        tokenPanel2Layout.setHorizontalGroup(
            tokenPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        tokenPanel2Layout.setVerticalGroup(
            tokenPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tokenPanel3Layout = new javax.swing.GroupLayout(tokenPanel3);
        tokenPanel3.setLayout(tokenPanel3Layout);
        tokenPanel3Layout.setHorizontalGroup(
            tokenPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        tokenPanel3Layout.setVerticalGroup(
            tokenPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tokenPanel4Layout = new javax.swing.GroupLayout(tokenPanel4);
        tokenPanel4.setLayout(tokenPanel4Layout);
        tokenPanel4Layout.setHorizontalGroup(
            tokenPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        tokenPanel4Layout.setVerticalGroup(
            tokenPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tokenPanel5Layout = new javax.swing.GroupLayout(tokenPanel5);
        tokenPanel5.setLayout(tokenPanel5Layout);
        tokenPanel5Layout.setHorizontalGroup(
            tokenPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        tokenPanel5Layout.setVerticalGroup(
            tokenPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tokenPanel6Layout = new javax.swing.GroupLayout(tokenPanel6);
        tokenPanel6.setLayout(tokenPanel6Layout);
        tokenPanel6Layout.setHorizontalGroup(
            tokenPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        tokenPanel6Layout.setVerticalGroup(
            tokenPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tokenPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chosenTokenPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ChoosePLayersLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chosenTokenPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chosenTokenPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tokenPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tokenPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chosenTokenPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chosenTokenPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chosenTokenPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tokenPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tokenPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(tokenPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ChoosePLayersLabel)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chosenTokenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tokenPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tokenPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoosePLayersLabel;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel1;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel2;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel3;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel4;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel5;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel6;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel tokenPanel1;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel tokenPanel2;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel tokenPanel3;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel tokenPanel4;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel tokenPanel5;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.TokenPanel tokenPanel6;
    // End of variables declaration//GEN-END:variables
}
