/*
 * PropertyTycoon Application by Zytom
 */
package zytom.proptycoon.view.NewGameMenu;

/**
 *
 * @author utopia
 */
public class ChoosePlayersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChoosePlayersPanel
     */
    public ChoosePlayersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoosePLayersLabel = new javax.swing.JLabel();
        chosenTokenPanel1 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel2 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel3 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel4 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel5 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();
        chosenTokenPanel6 = new zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel();

        ChoosePLayersLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        ChoosePLayersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChoosePLayersLabel.setText("Choose Players...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(chosenTokenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ChoosePLayersLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chosenTokenPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chosenTokenPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chosenTokenPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chosenTokenPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chosenTokenPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ChoosePLayersLabel)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chosenTokenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosenTokenPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoosePLayersLabel;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel1;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel2;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel3;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel4;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel5;
    private zytom.proptycoon.view.NewGameMenu.ChoosePlayers.ChosenTokenPanel chosenTokenPanel6;
    // End of variables declaration//GEN-END:variables
}
