/*
 * PropertyTycoon Application by Zytom
 */
package zytom.proptycoon.view.WhoStartsMenu;

 import zytom.proptycoon.view.NewGameMenu.ChoosePlayers.*;

/**
 *
 * @author utopia
 */
public class DiceValuePanel extends javax.swing.JPanel {

    int number;
    /**
     * Creates new form ChosenPlayerPanel
     */
    public DiceValuePanel(int x) {
        initComponents();
        this.number = number;
    }

    public String getIntAsString(){
        return String.valueOf(number);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aiLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 242));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(64, 64));
        setMinimumSize(new java.awt.Dimension(62, 62));
        setPreferredSize(new java.awt.Dimension(64, 64));
        setLayout(new javax.swing.OverlayLayout(this));

        aiLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        aiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aiLabel.setText(getIntAsString());
        aiLabel.setMaximumSize(new java.awt.Dimension(64, 64));
        aiLabel.setMinimumSize(new java.awt.Dimension(64, 64));
        aiLabel.setPreferredSize(new java.awt.Dimension(64, 64));
        add(aiLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiLabel;
    // End of variables declaration//GEN-END:variables
}
